from aim_fsm import *
import termProject.shared_context as shared_context
import vex

class GetHit(StateNode):
    """
    Looks for OrangeBarrel (the visual flash) as a sign of being hit.
    If hit, transition out.
    """
    def start(self, event=None):
        super().start(event)
        self.set_polling_interval(0.1)
        self.hit_detected = False

    def poll(self):
        # Look at the last observed vision objects
        for obj in self.robot.world_map.objects.values():
            if obj.__class__.__name__ == 'OrangeBarrelObj' and obj.is_visible:
                if not self.hit_detected:
                    self.hit_detected = True
                    # Let the central orchestrator/shared context know
                    shared_context.ScoreKeeper.score1 += 1 
                    print(f"[Robot 2] HIT DETECTED! Score is now R1: {shared_context.ScoreKeeper.score1}, R2: {shared_context.ScoreKeeper.score2}")
                    self.robot.erouter.post(TextMsgEvent("i_was_hit"))
                    self.post_success()

class UpdatePos(StateNode):
    """Periodically publish position to shared context."""
    def start(self, event=None):
        super().start(event)
    def poll(self):
        shared_context.ScoreKeeper.r2_pose = self.robot.pose

class UpdateLEDs(StateNode):
    """Turn on LEDs corresponding to the total loaded barrel count from shared context."""
    def start(self, event=None):
        super().start(event)
        self.set_polling_interval(0.1)
    def poll(self):
        count = shared_context.ScoreKeeper.barrel_count
        leds = [
            vex.LightType.LED1, vex.LightType.LED2, vex.LightType.LED3, 
            vex.LightType.LED4, vex.LightType.LED5, vex.LightType.LED6
        ]
        
        for i, led in enumerate(leds):
            if i < count:
                self.robot.robot0.led.on(led, vex.Color.GREEN)
            else:
                self.robot.robot0.led.off(led)

class Robot2Program(StateMachineProgram):
    def setup(self):
        #         pos_updater: UpdatePos()
        #         led_updater: UpdateLEDs()
        #         
        #         start_node: Print("Robot 2 Initialized") =C=> startup_flash
        #         startup_flash: Flash(vex.Color.BLUE, duration=2) =C=> hit_watcher
        #         hit_watcher: GetHit() =S=> flash_node
        #         
        #         flash_node: StateNode()
        #         flash_node_1: Say("Ouch") =C=> flash_node_2
        #         flash_node_2: Flash(vex.Color.RED) =C=> hit_watcher
        #         
        #         flash_node =C=> flash_node_1
        
        # Code generated by genfsm on Thu May 21 15:42:49 2026:
        
        pos_updater = UpdatePos() .set_name("pos_updater") .set_parent(self)
        led_updater = UpdateLEDs() .set_name("led_updater") .set_parent(self)
        start_node = Print("Robot 2 Initialized") .set_name("start_node") .set_parent(self)
        startup_flash = Flash(vex.Color.BLUE, duration=2) .set_name("startup_flash") .set_parent(self)
        hit_watcher = GetHit() .set_name("hit_watcher") .set_parent(self)
        flash_node = StateNode() .set_name("flash_node") .set_parent(self)
        flash_node_1 = Say("Ouch") .set_name("flash_node_1") .set_parent(self)
        flash_node_2 = Flash(vex.Color.RED) .set_name("flash_node_2") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(start_node) .add_destinations(startup_flash)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(startup_flash) .add_destinations(hit_watcher)
        
        successtrans1 = SuccessTrans() .set_name("successtrans1")
        successtrans1 .add_sources(hit_watcher) .add_destinations(flash_node)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(flash_node_1) .add_destinations(flash_node_2)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(flash_node_2) .add_destinations(hit_watcher)
        
        completiontrans5 = CompletionTrans() .set_name("completiontrans5")
        completiontrans5 .add_sources(flash_node) .add_destinations(flash_node_1)
        
        return self
