from aim_fsm import *
from aim_fsm.worldmap import RobotObj
import math

class FindClosestRobot(StateNode):
    """StateNode to traverse the world map and find the closest visible robot object."""
    def start(self, event=None):
        super().start(event)
        closest_robot = None
        min_dist = float('inf')
        
        for obj in self.robot.world_map.objects.values():
            if isinstance(obj, RobotObj):
                print(f"Checking {obj.name} | Visible: {obj.is_visible} | Pose: {obj.pose.x:.1f}, {obj.pose.y:.1f}")
                if obj.is_visible:
                    dist = math.sqrt((obj.pose.x - self.robot.pose.x)**2 + (obj.pose.y - self.robot.pose.y)**2)
                    print(f"  -> Distance: {dist:.1f}")
                    if dist < min_dist:
                        min_dist = dist
                        closest_robot = obj
                    
        if closest_robot is not None:
            self.post_data(closest_robot)
        else:
            self.post_failure()

class TestAimAtRobot(StateMachineProgram):
    """FSM program to find the closest robot, turn towards it, and kick the ball."""
    def setup(self):
        #         # Define states for finding, turning, waiting, and kicking
        #         finder: FindClosestRobot()
        #         turner: TurnToward()
        #         waiter: StateNode()
        #         kicker: Kick()
        #         complain: Say("I do not see the robot.")
        # 
        #         # Transitions: if found, turn, kick, then wait 1 seconds; if not found, complain.
        #         finder =D=> turner =C=> kicker =C=> waiter =T(1)=> finder
        #         finder =F=> complain =C=> finder
        
        # Code generated by genfsm on Tue May  5 10:51:13 2026:
        
        finder = FindClosestRobot() .set_name("finder") .set_parent(self)
        turner = TurnToward() .set_name("turner") .set_parent(self)
        waiter = StateNode() .set_name("waiter") .set_parent(self)
        kicker = Kick() .set_name("kicker") .set_parent(self)
        complain = Say("I do not see the robot.") .set_name("complain") .set_parent(self)
        
        datatrans1 = DataTrans() .set_name("datatrans1")
        datatrans1 .add_sources(finder) .add_destinations(turner)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(turner) .add_destinations(kicker)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(kicker) .add_destinations(waiter)
        
        timertrans1 = TimerTrans(1) .set_name("timertrans1")
        timertrans1 .add_sources(waiter) .add_destinations(finder)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(finder) .add_destinations(complain)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(complain) .add_destinations(finder)
        
        return self
